### ISSUE TITLE
Trouble with assignment

### ISSUE THREAD

**Issue by xq111** [twitter/torch-autograd#101]
I'm getting an error in some code involving assignment, which I would have thought the January update would have fixed. 

Here's a little bit of code that shows the problem

```
local ag = require "autograd"

local params = {w1 = torch.randn(1), w2 = torch.randn(1)}

function f(params)
    local t = torch.zeros(2)
    t[1] = torch.sum(params.w1)
    t[2] = torch.sum(params.w2)
    return ag.nn.Max(1)(t)[1]
end

function test()
    local df = ag.grad(f)
    local dParams, err = df(params)
    print(err)
end

test()
```
This gives the error:
```
bad argument #3 to '?' (torch.*Tensor expected, got table)
```

Any tips for what to change? Thanks!

**Comment by alexbw** [comment]
Are you running with grad(f,{optimize=true})?

**Comment by xq111** [comment]
That fixes it - thanks!

**Comment by alexbw** [comment]
Nice.

**Comment by Germanunkol** [comment]
Sorry for reviving an old topic, but can you explain why I need {optimize=true} set?

Is there a way to achieve similar behaviour without optimize=true? I've been fiddling with torch.select and torch.copy as an alternative, but then I run into errors which seem related to #96.
