### ISSUE TITLE
dot product in autograd

### ISSUE THREAD

**Issue by pdakwal** [twitter/torch-autograd#110]
Hi all,
Is dot product not yet supported by autograd. I am calling torch.dot(h1,h2) in gradient function. It gives me error 'dot product not yet supported by autograd'. If not, is there any workaround for this ?

**Comment by fmassa** [comment]
you can probably reshape your tensors to be `1xM` and `Mx1` and call `torch.mm` instead

**Comment by alexbw** [comment]
The `torch.dot` function does extremely weird things with matrices that are 2D, which is why we don't support it. For instance, it will unravel a 2D matrix to a 1D matrix silently, without telling you.

Use the `*` operator for matrix multiplies and dot products, or `torch.mm` explicitly.
