### ISSUE TITLE
torch.bmm

### ISSUE THREAD

**Issue by szagoruyko** [twitter/torch-autograd#111]
Hi, I can't find bmm anywhere, is it not supported? Any plans to add it?

**Comment by alexbw** [comment]
No, shouldn't be hard. A bit bandwidth limited for a week or so, but hope to get to it soon.

**Comment by szagoruyko** [comment]
@alexbw tell me if I can help. I'd like to learn the internals a bit.

**Comment by alexbw** [comment]
Happy to screenshare sometime soon, I can walk you through the mechanisms.

**Comment by aleSuglia** [comment]
Any news about this feature?

**Comment by claudiogreco** [comment]
I would be glad to see it implemented, too

**Comment by alexbw** [comment]
Closed by #136
