### ISSUE TITLE
Is it possible to use autograd.nn.AutoModule but not autograd.nn.AutoCriterion?

### ISSUE THREAD

**Issue by dlmacedo** [twitter/torch-autograd#119]
Dear Friend,

Is it possible to create a personalized model with autograd.nn.AutoModule but keeping using the standard criterions of torch, avoid using autograd.nn.AutoCriterion?

Thanks,

David

**Comment by alexbw** [comment]
Yes

**Comment by dlmacedo** [comment]
Dear friend,

Thank you for your answer.

Best regards,

David
