### ISSUE TITLE
How to create a module to behave like a simple activation function?

### ISSUE THREAD

**Issue by dlmacedo** [twitter/torch-autograd#120]
Dear Friends,

I would like to create a module with automodule to behave like just a simple activation function. No weight or bias to learn.

What is wrong with  the code below:

```
local SeLU  = function(input)
  local output 
  if input < -0.5 then
    output = 0.5*y
  elseif (input >= -0.5) and (input <= 0.5) then
    output = 1.0*y
  else
    output = 0.5*y
  end 
  return output
end

local autoSeLU = autograd.nn.AutoModule('AutoSeLU')(SeLU)

local vgg = nn.Sequential()
-- building block
local function ConvBNReLU(nInputPlane, nOutputPlane)
  vgg:add(nn.SpatialConvolution(nInputPlane, nOutputPlane, 3,3, 1,1, 1,1))
  vgg:add(nn.SpatialBatchNormalization(nOutputPlane,1e-3))
  vgg:add(autoSeLU)

  return vgg
end

```

**Comment by yangky11** [comment]
I had similar problem in https://github.com/twitter/torch-autograd/issues/117 and you can do something like `return output + 0 * bias + 0 * weight`..

**Comment by dlmacedo** [comment]
Dear yangky11,

Thanks for your help.

In this case, how should I call the autograd.nn.AutoModule? Do you think I call it without the weight and bias parameters, just like below:

`
local autoSeLU = autograd.nn.AutoModule('AutoSeLU')(SeLU)
`

Thanks,

David

**Comment by yangky11** [comment]
You still have to provide a dummy weight and bias as if they were used.

Kaiyu Yang

    _____________________________

**Comment by szagoruyko** [comment]
@dlmacedo yes you can, it was fixed in https://github.com/twitter/torch-autograd/pull/86

**Comment by dlmacedo** [comment]
Sadly, It didn't work...

I have got the following error:

> /home/dlm/torch/install/bin/luajit: /home/dlm/torch/install/share/lua/5.1/nn/Container.lua:67:  0ms | Step: 0ms         
> In 3 module of nn.Sequential:
> In 3 module of nn.Sequential:
> models/vgg_bn_drop_autograd_selu.lua:23: both torch.CudaTensor and (null) have no less-than operator

The code is below:

```
local SeLU  = function(input, weight, bias)
--local y = weight * input + bias
  local output 
  if input < -0.5 then
    output = 0.5 * y
  elseif (input >= -0.5) and (input <= 0.5) then
    output = 1.0 * y
  else
    output = 0.5 * y
  end 
  return output + 0 * torch.sum(weight) + 0 * torch.sum(bias)
end

local autogradSeLU = autograd.nn.AutoModule('AutoSeLU')(SeLU)
--local autogradSeLU = autograd.nn.AutoModule('AutoSeLU')(SeLU, tensor(1, 1),tensor(1, 1))

```
