### ISSUE TITLE
util.makeContiguous

### ISSUE THREAD

**Issue by mys007** [twitter/torch-autograd#123]
I am confused by the meaning of `util.makeContiguous` and its gradient being defined as `zeroGradient()`. There is also `torch.contiguous()` doing IMHO the same job, but having gradient `function(g,ans,x) return g end`. I have a strong feeling this is wrong. I have noticed this when trying to figure out why there is no backpropagation through `torch.view()`. I suggest `util.makeContiguous` get removed completely.

**Comment by alexbw** [comment]
Yep, you're right, will make this change today.

**Comment by alexbw** [comment]
You are correct, and I remove util.makeContiguous today and merge. GitHub is having some issues, so will do after the storm passes.
