### ISSUE TITLE
Better documentation about optimization

### ISSUE THREAD

**Issue by mys007** [twitter/torch-autograd#125]
The principle of optimization and the differences to the non-optimized mode should be better documented. I think the most important is the fact that the closure of the optimized (=compiled) function seems to be sealed at the moment of optimization, so for example this:
```
local v = 1
local f = function(params, x, y) return torch.sum(params.W[1]*v) end
````
won't reflect later changes of `v` once `f` is compiled, although it _does_ reflect the changes if optimization is turned off. On the other hand, changes to variables passed as arguments seem to be always reflected
```
local f = function(params, x, y, v) return torch.sum(params.W[1]*v) end
```
Moreover, there seems to be some effect on the functionality of `nn`-modules, although I didn't have the time to isolate the cases yet.

**Comment by alexbw** [comment]
Agreed. More description on the caveats of optimize mode is a good idea.

**Comment by alexbw** [comment]
Added some notes about this in the README
