### ISSUE TITLE
GPU support

### ISSUE THREAD

**Issue by Zealcui** [twitter/torch-autograd#134]
Hello folks,

Recently I'm working on a project using torch-autograd. When data size becomes large, it takes a lot more time to train. I'm trying to run our code on GPU and found no information related to switch torch-autograd into GPU mode. 

Any ideas?

Thanks!

**Comment by alexbw** [comment]
You can just change the type of your tensors to CudaType, either manually
or using myParams = util.cast(myParams, 'cuda'.

**Comment by Zealcui** [comment]
It worked! Thank you~
