### ISSUE TITLE
autograd initialization error

### ISSUE THREAD

**Issue by eladrich** [twitter/torch-autograd#149]
When trying to load autograd (require 'autograd'), the following error raises:

`...ser/torch-workspace/install/share/lua/5.1/trepl/init.lua:363: ...ser/torch-workspace/install/share/lua/5.1/trepl/init.lua:363: ...-workspace/install/share/lua/5.1/autograd/optim/init.lua:27: bad argument #1 to 'pairs' (table expected, got boolean)
stack traceback:
	[C]: in function 'error'
	...ser/torch-workspace/install/share/lua/5.1/trepl/init.lua:363: in function 'require'
	[string "_RESULT={require 'autograd'}"]:1: in main chunk
	[C]: in function 'xpcall'
	...ser/torch-workspace/install/share/lua/5.1/trepl/init.lua:630: in function 'repl'
	...-workspace/install/lib/luarocks/rocks/trepl/scm-1/bin/th:185: in main chunk
	[C]: at 0x00406240	`

I'm successfully working with autograd on a different machine (really awesome project!), so my guess is that I have some other package is out of date, or has changed.

**Comment by szagoruyko** [comment]
you should prob update your optim package `luarocks install optim`

**Comment by eladrich** [comment]
Yep, that was it
