### ISSUE TITLE
Error when using require autograd

### ISSUE THREAD

**Issue by bluechill52** [twitter/torch-autograd#15]
Hi, I've installed torch-autograd as mentioned in the github page. After installation whenever I try to run an example code, it throws the following error:

`/usr/local/share/lua/5.1/autograd/gradfuns.lua:290: table index is nil stack traceback: [C]: in function 'error' /home/monarch/torch/install/share/lua/5.1/trepl/init.lua:363: in function 'require' [string "_RESULT={require 'autograd'}"]:1: in main chunk [C]: in function 'xpcall' /home/monarch/torch/install/share/lua/5.1/trepl/init.lua:630: in function 'repl' ...arch/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:185: in main chunk [C]: at 0x00406670`

Then I noticed that the same error pops up when I just try to simply `require 'autograd'`. Help. Thanks in advance.

**Comment by alexbw** [comment]
We've changed the build system recently, so I would do a force-remove of autograd, and reinstall. If that fails, then re-install the torch distro. With the new build system, this should hopefully be smoother in the future.

**Comment by alexbw** [comment]
@bluechill52 any update? did a clean reinstall help?

**Comment by bluechill52** [comment]
Yeah the reinstall fixed the error. Thanks a lot.
