### ISSUE TITLE
'nodeApply' is nil when calling functionalized nn module

### ISSUE THREAD

**Issue by DaniloRezende** [twitter/torch-autograd#28]
When I run the code below
  
```lua
require 'env'
local t = require 'torch'
local ag = require 'autograd'

local n_enc = 10

local nn_enc = nn.Sequential()
:add(nn.SpatialConvolutionMM(1, 16, 3, 3, 1, 1, 1, 1))
:add(nn.Tanh())
:add(nn.SpatialMaxPooling(2,2,2,2))
:add(nn.SpatialConvolutionMM(16, 32, 3, 3, 1, 1, 1, 1))
:add(nn.Tanh())
:add(nn.Reshape(32*16*16))
:add(nn.ConcatTable()
	:add(nn.Linear(32*16*16, n_enc))
	:add(nn.Linear(32*16*16, n_enc))
	)

-- quick test
local x = torch.randn(10, 1, 32, 32)
local y_nn = nn_enc:forward(x)

-- Functionalize the model:
local ag_enc, enc_params = ag.functionalize(nn_enc)

local y_ag = ag_enc(enc_params, x)
print{params=params,y_ag=y_ag,y_nn=y_nn,x=x}
```

I get the error:
> autograd/nnwrapper.lua:291: attempt to call upvalue 'nodeApply' (a nil value)
> stack traceback:
>	[C]: in function 'nodeApply'
>	.../autograd/nnwrapper.lua:291: in function 'ag_enc'
>	test.lua:29: in main chunk

**Comment by alexbw** [comment]
Are you on the newest branch? We also switched to a new build system in the past week, so you might want to completely wipe your autograd install:

```
cd ~/wherever-you-keep-autograd/
git pull
rm -r build
luarocks remove --force autograd
luarocks make
```

Let me know if that doesn't work

**Comment by DaniloRezende** [comment]
Thank you for the quick reply, @alexbw.
I am using the master branch. I've pulled again and reinstalled, but still get the same error.

**Comment by clementfarabet** [comment]
@DaniloRezende I just merged a fix here: https://github.com/twitter/torch-autograd/pull/30 . Your code should work now.

**Comment by DaniloRezende** [comment]
Great, thank you very much.
