### ISSUE TITLE
Documentation Needed

### ISSUE THREAD

**Issue by kishorenayar** [twitter/torch-autograd#29]
Hi, 

 Thanks for creating autograd for torch7 and It's really cool, It will good if we have documentation for autograd package. Examples are good and it's helps to get started with this package but I think we need documentation too which will makes much more easier to use this package.

**Comment by alexbw** [comment]
Agreed. This is something we're trying to find time to improve.

**Comment by kishorenayar** [comment]
Cool.

**Comment by ronanmoynihan** [comment]
Hi, I've created a regression demo using a normal torch NN and a custom AutoCriterion designed to over or under predict using Autograd. https://github.com/ronanmoynihan/autograd-criterion

I haven't managed to get a gradCheck test working yet on the AutoCriterion,  
Do you have any example that shows this? Been trying some different things like in test.lua but still getting errors.

Thanks

**Comment by alexbw** [comment]
@ronanmoynihan Can you post your source code and specific errors in a new issue? We'd love to help you get up and running.

**Comment by ronanmoynihan** [comment]
Hi @alexbw it's no longer giving an error but getting some strange behaviour so I'll open a new issue.
Thanks.
