### ISSUE TITLE
Cloning AutoModule fails

### ISSUE THREAD

**Issue by vgire** [twitter/torch-autograd#42]
The following simple `AutoModule` fails at `module:clone()` with the error: `torch/File.lua:107: Unwritable object`
```lua
local autograd = require 'autograd'

local f = function(x, W, b)
  return x * W + torch.expand(b, torch.size(x, 1), torch.size(b, 2))
end

local batchSize = 5
local inputFeatures = 6
local outputFeatures = 7

local weight = torch.rand(inputFeatures, outputFeatures)
local bias = torch.rand(1, outputFeatures)
local module = autograd.nn.AutoModule('AutoModule')(f, weight, bias)

module:clone()
```
Is cloning not supported or is it a bug ?

Thanks

**Comment by alexbw** [comment]
Hey @vgire, I'll look into this. My guess is that we haven't implemented the machinery for `clone()` quite yet — the trouble is that a bit more logic than normal would have to happen when you clone an AutoModule. It might be that we just haven't implemented this method, but for now, you can just copy your `local module = ...` line as many times as you need to use that module. (cc @nkoumchatzky)

**Comment by nkoumchatzky** [comment]
@vgire #43 should help. Cloning was indeed not supported as autograd functions were not serializable. Also, this patch makes them loadable on-the-fly. I.e.: 

```lua
local autograd = require 'autograd'

local f = function(x, W, b)
  return x * W + torch.expand(b, torch.size(x, 1), torch.size(b, 2))
end

local batchSize = 5
local inputFeatures = 6
local outputFeatures = 7

local weight = torch.rand(inputFeatures, outputFeatures)
local bias = torch.rand(1, outputFeatures)
local module = autograd.nn.AutoModule('AutoModule')(f, weight, bias)

module:clone()
torch.save('module.th', module)
```

and 

```lua
local autograd = require 'autograd'
local module = torch.load('module.th')
```

should work.
Note that loading is possible only if autograd has been required.

**Comment by vgire** [comment]
@alexbw Thank you for your answer.
Copying `local module = ...` is what I ended up doing and is fairly easy in this self-contained example.
However, in my case, I build a siamese network where a top module is built as a composition of multiple modules and cloned with shared weight. The AutoModule is nested in this top module so it gets quite ugly.

@nkoumchatzky Thank you ! I'll see if it fixes my problem.

At the end it would be much simpler for me to write everything with autograd ;) but I am stuck on issue https://github.com/twitter/torch-autograd/issues/44.

**Comment by alexbw** [comment]
@vgire Does this solution work for you?

**Comment by vgire** [comment]
@alexbw I've pull @nkoumchatzky https://github.com/twitter/torch-autograd/pull/43 and it works out of the box now. Thank you both.
