### ISSUE TITLE
repeatTensor

### ISSUE THREAD

**Issue by noa** [twitter/torch-autograd#46]
I'm seeing the error:

/usr/local/share/lua/5.1/autograd/direct/DirectTape.lua:56: attempt to index field 'gradFun' (a nil value)

in a test involving repeatTensor. It looks like it might just not be supported yet?

**Comment by alexbw** [comment]
Good catch. We should support this operation, and also give better errors
here.

**Comment by luketwitter** [comment]
@noa you should now receive better error messages when using functions that have no gradient defined.
