### ISSUE TITLE
train-penn-lstm.lua crashes after finishing 1st epoch

### ISSUE THREAD

**Issue by jfsantos** [twitter/torch-autograd#48]
Running `th train-penn-lstm.lua` without passing any parameters (processing done on CPU, default parameters) I got the following error right after the first epoch finishes training and validation/test perplexities are computed:

```
Test set [just indicative, not used for training]...
Test set perplexity = 176.93627527427

Training Epoch #2
/Users/jfsantos/torch/install/bin/luajit: [string "return function(locals, rlocals, vlocals, Cla..."]:35: attempt to perform arithmetic on local 'p4' (a table value)
stack traceback:
	[string "return function(locals, rlocals, vlocals, Cla..."]:35: in function 'df'
	train-penn-lstm.lua:185: in main chunk
	[C]: in function 'dofile'
	...ntos/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:131: in main chunk
	[C]: at 0x010b42a320
```

`p4` seems to be an automatically generated variable inside the `df` function, but I have no clue on how I could debug that. Please let me know if I can run any specific tests to help fixing this issue.

**Comment by alexbw** [comment]
@jfsantos I can replicate this, will look into it

**Comment by alexbw** [comment]
Ok, I've reduced that example file to a small test case. It fails for `optimize=true`, but works for `optimize=false`.

Optimizations on the graph are not the culprit: commenting out optimizeGraph() had no effect on the error.

cc @luketwitter

Branch: https://github.com/twitter/torch-autograd/tree/lstmTestCase
File: https://github.com/twitter/torch-autograd/blob/lstmTestCase/examples/train-penn-lstm-testCase.lua

**Comment by luketwitter** [comment]
@jfsantos Thanks for the report, should be fixed now.

**Comment by jfsantos** [comment]
Just a heads-up: the example still breaks in the same place, with the same error message. Maybe there's something else missing?

**Comment by alexbw** [comment]
@luketwitter can confirm. republishing the test case branch.

**Comment by luketwitter** [comment]
@jfsantos Definitely seems to be working for me, and I had one more person try it. Can you make sure autograd is being rebuilt properly by doing:

```
luarocks remove autograd-scm-1.rockspec --force
luarocks make
```

**Comment by alexbw** [comment]
I was wrong earlier, the test case passes for me, I must not have cleaned my installation. @jfsantos?

**Comment by jfsantos** [comment]
Just installed it in another machine and the fix worked. Sorry for the noise!

**Comment by pdakwal** [comment]
I am facing the same problem while running train-penn-lstm.lua even before epoch 1 ends. Running with latest pull of auto-grad. Can't move to another machine. Please let me know if any fix for this ?

**Comment by alexbw** [comment]
Have you tried the commands above to force-uninstall autograd and reinstall it?

**Comment by zakattacktwitter** [comment]
Hi we recently posted a fix to the torch cat function that was crashing
often with larger LSTMs under autograd. The fix was merged here:

https://github.com/torch/torch7/pull/541

It might fix your crash.

Thanks,
Zak
