### ISSUE TITLE
functionalise on modules without parameters

### ISSUE THREAD

**Issue by noa** [twitter/torch-autograd#55]
It looks like autograd.functionalize assumes the passed module has a :parameters() method, which is not true for criterions for instance. The nnwrapper correctly handles this case for packages, however.

**Comment by alexbw** [comment]
This is a bug, and we should fix it. If you're comfortable poking around the code, a pull request would be very welcome!

**Comment by noa** [comment]
Here's a test case:

``` lua
   FunctionalizeCriterionModule = function()
      local input = {torch.rand(2,10), torch.randn(2,10)}
      local target = {torch.IntTensor{1,8}, torch.randn(2,10)}
      local nll = nn.ClassNLLCriterion()
      local mse = nn.MSECriterion()
      local pc = nn.ParallelCriterion():add(nll, 0.5):add(mse)
      local output1 = pc:forward(input, target)
      local pcf = autograd.functionalize(pc)
      local output2 = pcf(input, target)
      tester:asserteq(output1, output2, 'loss not equal')
      local f = function(x, y)
         return pcf(x.input, y)
      end
      tester:assert(gradcheck(f, {input=input}, target), 'incorrect gradients')
   end
```

I took a stab at a fix here:

https://github.com/noa/torch-autograd/blob/functionalize-criterion-module/src/nnwrapper.lua

but it's generating some weird code (the test above fails). Probably need someone more familiar with the code generation internals to debug -- it's probably just lack of familiarity on my part.

**Comment by luketwitter** [comment]
@noa you weren't too far off:

```
function(g,ans,x,y)
    grads = nodeApply(backFnDesc, nil, true, g, x, y)
end,
```

needs to be:

```
function(g,ans,x,y)
    return nodeApply(backFnDesc, nil, true, g, x, y)
end,
```

And the 'name' field in the function descriptor, which you currently have as  name = torch.typename(input), needs to be something that's usable as a local variable in the generated code, e.g. "nn.Criterion" is not, because of the period.

**Comment by alexbw** [comment]
@noa This should be fixed in 081f595. Let me know if it works for you.

**Comment by noa** [comment]
@luketwitter Thanks, good catch 

@alexbw It looks like 081f595 has trouble with compound criterions like ParallelCriterion in my test above, which do not have a :type() method. Specifically, I'm seeing:

```lua
/usr/local/share/lua/5.1/autograd/nnwrapper.lua:365: attempt to call method 'type' (a nil value)
```

**Comment by alexbw** [comment]
I'll have a fix for it soon.

**Comment by alexbw** [comment]
Two issues:
The call signature for criterions are different, and had to be special-cased.
You have table-valued inputs, which had to be special-cased.

Should be fixed in: 55e20e.

**Comment by noa** [comment]
@alexbw Great, 55e20ee works for me. Thanks!
