### ISSUE TITLE
wrapping plain numbers (not tensors)

### ISSUE THREAD

**Issue by noa** [twitter/torch-autograd#56]
This is more of a usage question than an issue: is any special handling needed for constant scaling factors? Specifically, will autograd properly handle constants which are (1) upvalues and (2) passed arguments (separate from parameters)? For instance:

```lua
local loss = lossf(yhat,y) * a1 + lossf(zhat,z) * a2
```

where ```a1``` and ```a2``` are numbers.

**Comment by alexbw** [comment]
With `optimize=true`, upvalues are not recommended, because they will be included as constants when the function is compiled. You can get around this by passing them in as parameters. I believe that if you pass them in as arguments, either as params or otherwise, it should be fine.

**Comment by luketwitter** [comment]
As long as they're truly constant, upvalues are fine. If they're changing between invocations of df, that will cause problems.
