### ISSUE TITLE
Latest commit increased memory requirements in both modes (direct and cached)

### ISSUE THREAD

**Issue by noa** [twitter/torch-autograd#62]
Just a heads up that it looks like one of the latest commits blew up memory requirements. Probably cd6b9e0. Error below; it's asking for more than 12GB, which might indicate a bug? The same trainable function was working with direct mode prior to the new commit, but I did not test it with cached mode.

```
/usr/local/bin/luajit: ...re/lua/5.1/autograd/runtime/codegen/backend/lua/init.lua:262: cuda runtime error (2) : out of memory at /tmp/luarocks_cutorch-scm-1-8457/cutorch/lib/THC/THCStorage.cu:44
stack traceback:
        [C]: in function 'new'
        ...re/lua/5.1/autograd/runtime/codegen/backend/lua/init.lua:262: in function 'createSymbolTable'
        ...re/lua/5.1/autograd/runtime/codegen/backend/lua/init.lua:413: in function 'generateCode'
        ...re/lua/5.1/autograd/runtime/codegen/backend/lua/init.lua:574: in function 'generateFn'
        /usr/local/share/lua/5.1/autograd/runtime/codegen/init.lua:66: in function 'd_train_net'
```

**Comment by luketwitter** [comment]
Thanks for the heads up - we should probably have a test for this...

**Comment by luketwitter** [comment]
@noa should be fixed, sorry about that. Did a major refactor, and tensor pooling got turned off.

**Comment by noa** [comment]
Memory error is fixed, thanks. Now I'm seeing:

```/usr/local/bin/luajit: ...re/lua/5.1/autograd/runtime/codegen/backend/lua/init.lua:578: failed to parse generated code```

It's possible the refactor exposed a bug on my end, as this code worked in prior versions.

**Comment by luketwitter** [comment]
Feel free to paste the generated code (it should print out above that error), and I'll take a look too.

**Comment by noa** [comment]
Not positive if this fixed the issue or simply hid it, but in the code below, I replaced the 3 commented out lines with those below and I'm no longer getting an error:

```lua
      -- local tmp1 = torch.select(yhat_2, 2, t)
      -- local ystar = torch.select(y, 1, t)
      -- local tmp2 = torch.select(tmp1, 2, ystar)
      local tmp1 = torch.select(yhat_2, 2, t)
      local ystar = torch.narrow(y, 1, t, 1)
      local tmp2 = torch.index(tmp1, 2, ystar)
```

**Comment by luketwitter** [comment]
Probably just hid it, but hard to say without seeing the error or a larger example.

**Comment by yongfei25** [comment]
Hi, I'm getting syntax error in the generated code as well

```lua
return function(locals, rlocals, vlocals, ClassNLLCriterion1)
local nn = require('autograd').nn
local util = require('autograd.util')
-- ...
return function(p1, p2)
  locals[1] = torch_view(c1, 1, 400204)
  -- ...
  locals[21] =  -  -- syntax error
  locals[22] =  - 

  -- and then the code contains printed tensor.
  torch_cat(rlocals[31], {Columns 1 to 6
  -4.8113e-03  5.4577e-02 -6.2334e-02 -4.5157e-02 -1.3599e-02 -1.0038e-02

  Columns 7 to 12
  -9.8425e-02 -5.9643e-02 -4.5707e-02  2.6064e-02 -8.1065e-02  7.4847e-02
  -- ...
  Columns 400003 to 400004
  -4.0643e-02  3.6942e-02
  [torch.DoubleTensor of size 1x400004]
  , locals[21], locals[22]}, 1)

 -- ...
  torch_mm(rlocals[32], locals[19], p1.answer.Wa)
  return {
        answer = {
            W = rlocals[120],
            bm = rlocals[117],
            b = rlocals[116],
            Wm = rlocals[102],
            Wa = rlocals[58],
        },
    }, n194_1
end
end
```

**Comment by luketwitter** [comment]
Wow, that's quite strange. If you can send me a self contained example, I'll fix it and add something like this to the tests so it doesn't happen again.

**Comment by luketwitter** [comment]
@noa latest master should use substantially less memory than any prior version (2-4x less, on average).

**Comment by noa** [comment]
@luketwitter awesome, I tested it and no issues on my end. I'm also no longer seeing any code generation issues, so I'd call this issue resolved.
