### ISSUE TITLE
non-optimizing still optimizes

### ISSUE THREAD

**Issue by ngoodman** [twitter/torch-autograd#65]
i think it's the case that somewhere around commit cd6b9e0160c8c8e41263147b8ab11be0a88aae41 optimization started happening even when not in optimization mode. main.lua says this around line 32:
~~~
   if optimize then
      return RuntimeCodegen.create(fn, opt)
   else
      return RuntimeDirect.create(fn, opt)
   end
~~~
i believe the test should be on `opt.optimize`?

**Comment by luketwitter** [comment]
yep, good catch. 'optimize' is the name of a local function, and it's always true - lame...
