### ISSUE TITLE
Errors with the "Reorganize codegen" commit

### ISSUE THREAD

**Issue by brianzhang01** [twitter/torch-autograd#69]
Commit 29a2399bca22b5fd7c52aff6757d068928e2fa1b introduced various errors that should get fixed.

In two places, the require paths were not updated correctly:

In src/gradfuns.lua, line 2 should be
local DirectNode = require 'autograd.runtime.direct.DirectNode'

In src/runtime/direct/DirectTape.lua, line 3 should be
local DirectNode = require 'autograd.runtime.direct.DirectNode'

The reason these were not caught by tests is because of an error that was simultaneously introduced in CMakeLists.txt. If you take a look at https://travis-ci.org/twitter/torch-autograd/jobs/96998417 you see that the files under src/runtime are getting built multiple times. This has the effect of installing the src/runtime/direct/DirectNode.lua file into autograd/direct/DirectNode.lua, an incorrect location.

Instead, lines 15 - 18 of CMakeLists.txt:

INSTALL(DIRECTORY "src/runtime/direct" DESTINATION "${Torch_INSTALL_LUA_PATH_SUBDIR}/autograd")
INSTALL(DIRECTORY "src/runtime/codegen" DESTINATION "${Torch_INSTALL_LUA_PATH_SUBDIR}/autograd")
INSTALL(DIRECTORY "src/runtime/codegen/backend" DESTINATION "${Torch_INSTALL_LUA_PATH_SUBDIR}/autograd")
INSTALL(DIRECTORY "src/runtime/codegen/backend/lua" DESTINATION "${Torch_INSTALL_LUA_PATH_SUBDIR}/autograd")

should be removed. I wonder if there's a way to even install all the files under src/, rather than having to list out all the subfolders.

**Comment by luketwitter** [comment]
Thanks for the report! Fixed.
