### ISSUE TITLE
"expected FloatTensor in tensor array" error

### ISSUE THREAD

**Issue by as1986** [twitter/torch-autograd#88]
After pulling the latest commits I am running into the following error on the LSTM example:
[string "return function(locals, rlocals, vlocals, cri..."]:254: expected FloatTensor in tensor array
stack traceback:
	[C]: in function 'torch_FloatTensor_cat'
	[string "return function(locals, rlocals, vlocals, cri..."]:254: in function 'df'
	train-penn-lstm.lua:183: in main chunk
	[C]: in function 'dofile'
	....edu/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00405b50

Similar errors also occur when I changed to the CUDA backend. What has gone wrong?

**Comment by alexbw** [comment]
Thanks for the bug report. The API had changed a bit. Well look into it and
have a fix soon.

**Comment by andresy** [comment]
additional note: if one replaces
```lua
local df =  d(f, { optimize = true })
```
with
```
local df =  d(f, { optimize = false })
```
it also fails with:
```
RecurrentLSTMNetwork.lua:80: attempt to call field 'cat' (a nil value)
stack traceback:
	...r7/share/lua/5.1/autograd/model/RecurrentLSTMNetwork.lua:80: in function 'lstm1'
	train-penn-lstm.lua:93: in function 'fun'
	...sr7/share/lua/5.1/autograd/runtime/direct/DirectTape.lua:103: in function 'funOnly'
	...sr7/share/lua/5.1/autograd/runtime/direct/DirectTape.lua:198: in function 'df'
	train-penn-lstm.lua:183: in main chunk
```
thanks for looking into this!

**Comment by andresy** [comment]
the example runs if one hacks the above with:
```
local df =  d(f, { optimize = true,
                   debugHook = function()
                   end
})
```

**Comment by alexbw** [comment]
I have DirectMode working (optimize=false) in a branch here: https://github.com/twitter/torch-autograd/tree/lstm.

Still getting funky errors in optimized mode.

```
/Users/Alex/anaconda/bin/lua: invalid arguments: FloatTensor DoubleTensor FloatTensor ..] ETA: 1h33m | Step: 120ms
expected arguments: [*FloatTensor*] FloatTensor FloatTensor
stack traceback:
	[C]: in ?
	[C]: in function 'torch_cmul'
	[string "return function(locals, rlocals, vlocals, mod..."]:260: in function <[string "return function(locals, rlocals, vlocals, mod..."]:32>
	(...tail calls...)
	train-penn-lstm.lua:169: in main chunk
	[C]: in function 'dofile'
	/Users/Alex/anaconda/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: in ?
```

**Comment by alexbw** [comment]
Yeah, and @andresy now that DirectMode works, adding in a debug hook makes optimize=true works. Very weird cc @luketwitter

**Comment by alexbw** [comment]
The mystery deepens: computing `util.cat(hs, 2)` twice (not pre-computing, recomputing it) makes optimize=true work.

https://github.com/twitter/torch-autograd/blob/lstm/src/model/RecurrentLSTMNetwork.lua#L81

**Comment by clementfarabet** [comment]
One note: `torch.cat` still doesn't handle auto-type (as in `torch.cat({torch.FloatTensor(1), torch.FloatTensor(1)})` will fail, so one needs to use `torch.FloatTensor.cat({torch.FloatTensor(1), torch.FloatTensor(1)})`). We may have introduced a code path (in `optimize=false` mode) that makes this mistake?

**Comment by alexbw** [comment]
util.cat does auto-type, and I changed torch.cat to util.cat in the models
in the lstm branch

**Comment by clementfarabet** [comment]
OK, great.

**Comment by luketwitter** [comment]
@andresy @as1986  This should be fixed now. Thanks for the bug report!

**Comment by andresy** [comment]
thanks guys :+1:

**Comment by as1986** [comment]
thanks!
