### ISSUE TITLE
Failed to parse generated code

### ISSUE THREAD

**Issue by yongfei25** [twitter/torch-autograd#93]
Hi,

I'm having problem running with optimized enabled. 
I print out the error of `loadstring/load` function in `init.lua`, here's the error. 

```
[string "return function(locals, rlocals, vlocals, mod..."]:634: function at line 38 has more than 60 upvalues	
/home/yongfei/torch/install/bin/luajit: ...re/lua/5.1/autograd/runtime/codegen/backend/lua/init.lua:760: failed to parse generated code
```

And here's the generated code.

https://gist.github.com/yongfei25/8992651ec5fd55805b7f

The error above was running on CPU, when I try on GPU, got

```
/home/ubuntu/lib/torch/install/bin/luajit: ...nstall/share/lua/5.1/autograd/runtime/codegen/Source.lua:35: invalid value (table) at index 1 in table for 'concat'
stack traceback:
	[C]: in function 'concat'
	...nstall/share/lua/5.1/autograd/runtime/codegen/Source.lua:35: in function 'symbolPath'
```

**Comment by alexbw** [comment]
Can you also paste the function that you're passing to autograd?

**Comment by yongfei25** [comment]
@alexbw, I think it is a fairly complex model. Here's the code https://gist.github.com/yongfei25/2199be6caa5d97522bcd

I included the link of the to classes in the comment.

**Comment by luketwitter** [comment]
@yongfei25 should be fixed, let me know if you have any issues

**Comment by yongfei25** [comment]
@luketwitter thanks :). It fixed the upvalue problem. It bump into another error now. Could you help me to look at this error too?

```
[string "return function(locals, rlocals, vlocals, obj..."]:1211: chunk has too many syntax levels
```

**Comment by luketwitter** [comment]
As a workaround, try passing inline = false to the autograd options.

**Comment by yongfei25** [comment]
It worked! Thanks !

**Comment by luketwitter** [comment]
Great. I'll try to fix that problem soon, but for now, use that.
