### ISSUE TITLE
Grad for cmin and cmax

### ISSUE THREAD

**Issue by yongfei25** [twitter/torch-autograd#95]
Hi,

Could we have `cmin` and `cmax` function supported :) ?

**Comment by alexbw** [comment]
Sure! Could you do the project a favor and list all the other grads you
might want? That way I can do them all in a row.

**Comment by yongfei25** [comment]
@alexbw, thanks :) . Looks like I'm only missing `cmin` and `cmax`. 

Does the others operations like `cmul, cdiv, exp, cat` etc uses the same Tensor in optimized mode? Otherwise it would consume too much memory to spawn new Tensor every time they are called.

**Comment by alexbw** [comment]
In optimized mode, we do tensor re-use when we compile the forward pass.
However, when the user writes their forward-pass, everything will appear
purely functional (with the exception of assignment, e.g. x[i] = k).

**Comment by yongfei25** [comment]
I see, so the function compiled in optimized mode will reuse Tensor as much as possible, is there anything I shouldn't do to avoid allocating new Tensor in optimized mode?


And could we have torch.clamp supported as well? Thanks  :)

**Comment by alexbw** [comment]
clamp is supported currently.

**Comment by alexbw** [comment]
cmin and cmax now in a50d2af

**Comment by yongfei25** [comment]
thanks :)
